### ISSUE TITLE
Adding a new worker host fails the ansible playbook deploy

### ISSUE THREAD

**Issue by sjdemartini** [Quansight/qhub-hpc#111]
I've gone from a one-node setup in my `inventory` file, like:

```
hpc-master-node ansible_host=xxx.xxx.xxx.xxx ansible_port=22 ansible_user=my_username

[hpc-master]
hpc-master-node

[hpc-worker]
hpc-master-node
```

to:

```
hpc-master-node ansible_host=xxx.xxx.xxx.xxx ansible_port=22 ansible_user=my_username
hpc-worker-02 ansible_host=xxx.xxx.xxx.xxx ansible_port=22 ansible_user=my_username

[hpc-master]
hpc-master-node

[hpc-worker]
hpc-worker-02
```

However, this led to a crash during the Ansible deploy:

```
TASK [hosts : Ensure hosts exist within /etc/hosts] ********************************************************************************************************
Friday 11 March 2022  10:52:37 -0800 (0:00:00.040)       0:00:04.423 **********
ok: [hpc-master-node] => (item=hpc-master-node)
fatal: [hpc-master-node]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ipv4'\n\nThe error appears to be in '/Users/.../qhub-hpc/roles/hosts/tasks/main.yaml': line 2, column 4, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n - name: Ensure hosts exist within /etc/hosts\n   ^ here\n"}
ok: [hpc-worker-02] => (item=hpc-master-node)
fatal: [hpc-worker-02]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ipv4'\n\nThe error appears to be in '/Users/.../qhub-hpc/roles/hosts/tasks/main.yaml': line 2, column 4, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n - name: Ensure hosts exist within /etc/hosts\n   ^ here\n"}
```

Perhaps this is related to https://github.com/Quansight/qhub-hpc/blob/323a9342e913442f6f2df24f0e79176f99366d51/playbook.yaml#L4-L9 (one of the only mentions of ipv4 that I see in this repo)?—that task is skipped for me every time

**Comment by costrouc** [comment]
Could you try setting the `internal_interface` variable within the `host_vars/<hostname>.yaml` to override the default interface name that is being used for all nodes. My guess would be that the nodes have different interface names. 

Also to me it looks like the error is happening here https://github.com/Quansight/qhub-hpc/blob/main/roles/hosts/tasks/main.yaml#L1-L9

**Comment by sjdemartini** [comment]
Yeah, `Ensure hosts exist within /etc/hosts` is indeed the task that was crashing (I thought the other task that was getting skipped was related but perhaps not). Updating the `internal_interface` in `host_vars` did the trick. Closing this issue. Thanks!

**Comment by sjdemartini** [comment]
I spoke too soon. Setting that in `host_vars/<hostname>.yaml` seems to have resolved things for the worker node, but now broken things for the master node:

```
TASK [hosts : Ensure hosts exist within /etc/hosts] ********************************************************************************************************
Friday 11 March 2022  12:48:31 -0800 (0:00:00.041)       0:00:04.528 **********
ok: [hpc-master-node] => (item=hpc-master-node)
fatal: [hpc-master-node]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ipv4'\n\nThe error appears to be in '/Users/.../qhub-hpc/roles/hosts/tasks/main.yaml': line 2, column 4, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n - name: Ensure hosts exist within /etc/hosts\n   ^ here\n"}
ok: [hpc-worker-02] => (item=hpc-master-node)
ok: [hpc-worker-02] => (item=hpc-worker-02)
```

It looks like it's doing something strange with iterating over the "items" for that `Ensure hosts exist within /etc/hosts` task, where it runs each node's operation on every host (e.g. notice  that it does `[hpc-worker-02] => (item=hpc-master-node)` followed by `ok: [hpc-worker-02] => (item=hpc-worker-02)`).
