### ISSUE TITLE
Add options for dask_gateway to specify environment

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-hpc#12]
Add ability to choose conda environment on dask work via `gateway.cluster_options`

**Comment by costrouc** [comment]
Had an idea on how to implement this in pseudo code. Add to the dask gateway.

```
environments = []
for environment in `conda env list`:
     if `conda list -n environment` has dask distributed installed:
          environments.append(environment)
```

This is how we can get the environments and use this variable. Then on the dask gateway exposes the following slurm options.

```
c.SlurmClusterConfig.scheduler_cmd = "/opt/miniconda/bin/dask-scheduler"
c.SlurmClusterConfig.worker_cmd = "/opt/miniconda/bin/dask-worker"
```

So we would set the path to 

 - `/opt/conda/envs/<environment-name>/bin/dask-scheduler`
 - `/opt/conda/envs/<environment-name>/bin/dask-worker`
