### ISSUE TITLE
Remove dashes from group names

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-hpc#15]
The tests have ansible groupnames such as `hpc01-test`. Dashes are considered invalid, and this throws a warning. Change test groupnames to have underscores instead of dashes

**Comment by costrouc** [comment]
```
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "{'-'}" in group name (hpc-master)
Not replacing invalid character(s) "{'-'}" in group name (hpc-worker)
```

Update qhub-hpc to use hpc_master and hpc_worker respectively to silence this error.
