### ISSUE TITLE
CDS limitations around shared dashboards

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub-hpc#74]
The current CDS solution has a design that could limit my usecase.  I present the following situation and proposed changes. I'd like to understand the complexity and level of effort of each change. 

I lay out 4 changes to the workflow: 
1) git repo/project registration 
2) launch as user 
3) user resource management and kill/processes, and 
4) weekly Jupyter server clean up.  

Today's CDS workflow works well for creating a dashboard or voila notebook and sharing it casually within a small group of users.  The publisher will create the dashboard and spin up a resource for any user to use.  As we imbeds user credentials in Jupyter server, the user of a dashboard will now have access to the publisher's database and file privileges.  This works for limited use cases, but when we consider this workflow for generic applications broadly it could create a security risk and decrease the quality of an audit trail, by losing who is interacting with data and file.  There are additional issues, where a publisher may have stopped the server and a user wouldn’t have the tools to start it or access it.  We also worry about resource planning.  It's hard to know a priori if a user has 1 or 10 users, but we would need to provision for 10.  Lastly, under this model dashboards are tied to a user and not a project or team, so if the dashboard is extended by another user the dashboard will move, and possibly have the old copy live until the original publisher disables it.

I would like Quansight to consider an alternative solution:

1) Publishers would register a git repo with the CDS.  The repo would be a "project" or folder.  CDS will look for a file called "cds.yaml" which will list the files to be run as CDS dashboards along with the environment settings.  To add a new dashboard a user will include the files, add the instructions to the yaml file, and then do a git push/ and pull.  Optional: CDS can respect the directory structure of repo for creating more logical grouping for users.  To be determined, what pulls these changes, or is a pull part of the startup process.

2) The dashboard would launch on a Jupyter server belonging to the end user.  This server could either be the "default" named server, a sever of a specific name, such as cds.  I would propose the later so that a dashboard would not affect a user's research in a different area. 

3) Similar to Jupyter Tree and Lab, We will probably also want to make memory usage observable and simple to kill CDS dashboard on your server. 

4) I think we will want a tool that kills all CDS servers on a weekly basis, weekend reset.  This will free up resources, particularly for users who do a quick look and see.

 

What this fixes:

dashboards are owned by project/team, not a person.
we use git to manage code access, changes etc. reverting new version simple; git has access controls
user capacity is easier to manage
easier to launch and manage more dashboards
user has control of what dashboard kernels they are running; users can see their resources use
use case for dashboards widen when users are acting as themselves: inserts and data changes to sql is controlled better with clear audit, file browsing and access is cleaner
avoids the use of a utility account that we would probably consider using
 

Downsides: for first dashboard, users will need to wait to launch server, and then launch the dashboard.

**Comment by danlester** [comment]
We are working on some of this now in a discrete project.
