### ISSUE TITLE
Jupyterlab won't spin up 

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub-hpc#79]
Running ubuntu2004 tests, jupyterhub starts, but when I log on to jupyterhub, I'm unable to spin up a jupyterlab session for example-user.  The slurmspawner logs are given below:

>vagrant@hpc01-test:/home/example-user$ cat .jupyterhub_slurmspawner_6.log 
/opt/conda/envs/jupyterlab/bin/jupyterhub-singleuser
running command batchspawner-singleuser jupyterhub-singleuser --ip=0.0.0.0 --SingleUserNotebookApp.default_url=/lab
srun: error: Couldn't find the specified plugin name for mpi/pmi_v2 looking at all files
srun: error: cannot find mpi plugin for mpi/pmi_v2
srun: error: cannot create mpi context for mpi/pmi_v2
srun: error: invalid MPI type 'pmi_v2', --mpi=list for acceptable types

**Comment by Adam-D-Lewis** [comment]
Running the below command lists the MPI types

>vagrant@hpc01-test:/home/example-user$ srun --mpi=list
srun: MPI types are...
srun: pmix_v3
srun: pmi2
srun: none
srun: openmpi
srun: pmix

**Comment by Adam-D-Lewis** [comment]
Commenting out the # MpiDefault: pmi_v2 line in all.yaml gets around the problem for now.

**Comment by Adam-D-Lewis** [comment]
@costrouc any thoughts?  Should I jsut switch pmi_v2 to pmi2?

**Comment by costrouc** [comment]
@tylerpotts would know more about this setting. But I don't see any issues with uncommenting pmi_v2.

**Comment by tylerpotts** [comment]
@Adam-D-Lewis I'm not familiar with this particular setting. Doing some googling, it seems that [based on these docs](https://slurm.schedmd.com/mpi_guide.html) `pmi2` or `pmi2_v2` can be used: 

```
If OpenMPI is configured with --with-pmi either pmi or pmi2, the OMPI jobs can be launched directly using the srun command. This is the preferred mode of operation. If the pmi2 support is enabled, the option '--mpi=pmi2' or '--mpi=pmi2_v2' must be specified on the srun command line. Alternately configure 'MpiDefault=pmi' or 'MpiDefault=pmi_v2' in slurm.conf.
```

Currently you're using `pmi_v2` (which only contains a single `2`) instead of `pmi2_v2`. I'd try switching to the one with two `2`s, or switching to `pmi2`

**Comment by tylerpotts** [comment]
Also in agreement with @costrouc that commenting it out is a valid solution. Without specifying the version my *guess* is that slurm will pick a default one

**Comment by Adam-D-Lewis** [comment]
resolved
