### ISSUE TITLE
Add ability to override variables from a separate repo for deployment customization

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub-hpc#88]
Goal is to avoid forking/rebasing model of managing the deployment

**Comment by costrouc** [comment]
Thanks for opening this issue @Adam-D-Lewis. This is a priority for a client deployment since we want to avoid the forking model for deployments with clients. Going to brainstorm on this issue.

**Comment by Adam-D-Lewis** [comment]
Some additional thoughts.  We should define which features this solution should allow users to be able to customize.  I've listed some possible ones below.

## Possible features of solution
1. can exclude any task if desired
2. can can insert custom tasks
3. can change which environments are installed

1 could perhaps be done with by including variables for each task (or perhaps group of tasks) which if set prevent the task from running.  This feels a little clunky but could work.

2 could be done with `include tasks` and `when` e.g.
```yaml
 - name: Run custom tasks
   include_tasks: "{{ custom_tasks_path }}"
   when: custom_tasks_path is defined
```
Users could insert custom tasks at the end of the playbook.

3 feels pretty straight forward by just making the environment directory an ansible variable

Alternatively, 1 & 2 could be done perhaps more elegantly and flexibly by using the [Python API](https://docs.ansible.com/ansible/latest/dev_guide/developing_api.html) directly, but it would likely require more effort, and the python API is not officially supported for external use.

**Comment by Adam-D-Lewis** [comment]
closed by https://github.com/Quansight/qhub-hpc/pull/95
